"""Repeatable Wealth engine strategy and monitor modules."""

from engines.wealth.deterministic.mean_reversion_lab import (
    LAB_NAME,
    PHASE_ID,
    REQUIRED_LABELS,
    MeanReversionBacktestResult,
    MeanReversionConfig,
    build_mean_reversion_signals,
    build_report_payload,
    render_markdown_report,
    run_research_backtest,
    safety_manifest,
    signal_definitions,
    write_research_report,
)
from engines.wealth.deterministic.wealth_backtester import (
    BACKTESTER_NAME,
    CostBreakdown,
    WealthBacktestConfig,
    WealthCostSlippageAssumptions,
    WealthBacktestResult,
    build_benchmark_returns,
    build_report_payload as build_wealth_backtester_report_payload,
    compute_return_metrics,
    default_conservative_cost_slippage_hook,
    default_linear_cost_hook,
    render_markdown_report as render_wealth_backtester_markdown_report,
    run_wealth_backtest,
    safety_manifest as wealth_backtester_safety_manifest,
    write_research_report as write_wealth_backtester_research_report,
)
from engines.wealth.deterministic.wealth_backtester import PHASE_ID as WEALTH_BACKTESTER_PHASE_ID
from engines.wealth.deterministic.wealth_regime_filters import (
    FILTER_NAME,
    WealthRegimeFilterConfig,
    WealthRegimeFilterResult,
    build_report_payload as build_wealth_regime_filter_report_payload,
    build_wealth_regime_filters,
    evaluate_wealth_regime_filters,
    regime_filter_definitions,
    render_markdown_report as render_wealth_regime_filter_markdown_report,
    safety_manifest as wealth_regime_filter_safety_manifest,
    write_research_report as write_wealth_regime_filter_research_report,
)
from engines.wealth.deterministic.wealth_regime_filters import PHASE_ID as WEALTH_REGIME_FILTER_PHASE_ID

__all__ = [
    "LAB_NAME",
    "PHASE_ID",
    "REQUIRED_LABELS",
    "BACKTESTER_NAME",
    "FILTER_NAME",
    "WEALTH_BACKTESTER_PHASE_ID",
    "WEALTH_REGIME_FILTER_PHASE_ID",
    "CostBreakdown",
    "MeanReversionBacktestResult",
    "MeanReversionConfig",
    "WealthBacktestConfig",
    "WealthCostSlippageAssumptions",
    "WealthBacktestResult",
    "WealthRegimeFilterConfig",
    "WealthRegimeFilterResult",
    "build_benchmark_returns",
    "build_mean_reversion_signals",
    "build_report_payload",
    "build_wealth_backtester_report_payload",
    "build_wealth_regime_filter_report_payload",
    "build_wealth_regime_filters",
    "compute_return_metrics",
    "default_conservative_cost_slippage_hook",
    "default_linear_cost_hook",
    "evaluate_wealth_regime_filters",
    "regime_filter_definitions",
    "render_wealth_backtester_markdown_report",
    "render_wealth_regime_filter_markdown_report",
    "render_markdown_report",
    "run_research_backtest",
    "run_wealth_backtest",
    "safety_manifest",
    "wealth_backtester_safety_manifest",
    "wealth_regime_filter_safety_manifest",
    "signal_definitions",
    "write_wealth_backtester_research_report",
    "write_wealth_regime_filter_research_report",
    "write_research_report",
]
